# name: Web, Android, iOS Build
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:
#     name: Web, Android, iOS Build
#     env:
#       my_secret: ${{secrets.TOKEN}}
#     # This job will run on macos virtual machine
#     runs-on: macos-latest
#     steps:
#       # Setup Java environment in order to build the Android app.
#       - uses: actions/checkout@v1
#       - uses: actions/setup-java@v1
#         with:
#           java-version: '12.x'
#       # Setup the flutter environment.
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: stable
#           flutter-version: '2.8.1'
#       - run: flutter config --enable-web
#       - run: flutter clean
#       - run: flutter pub get
#       # Flutter android apk build command.
#       - run: flutter build apk --debug --split-per-abi
#       # Flutter ios ipa build command.
#       - run: |
#           flutter build ios --no-codesign
#           cd build/ios/iphoneos
#           mkdir Payload
#           cd Payload
#           ln -s ../Runner.app
#           cd ..
#           zip -r app.ipa Payload
#       # Upload generated apk to the artifacts.
#       - name: Push to Releases
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
#           tag: v1.0.${{ github.run_number }}
#           token: ${{ secrets.TOKEN }}
#       # Flutter web release command.
#       - run: flutter build web --release
#       - run: |
#           cd build/web
#           git init
#           # type configurations: your user.email and user.name followed lines 
#           # git config --global user.email your_email 
#           # git config --global user.name your_name 
#           git config --global user.email sabikrahat72428@gmail.com
#           git config --global user.name sabikrahat
#           git status
#           # change this remote url for examle your remote url is https://github.com/sabikrahat/kick_start.git then the following:
#           git remote add origin https://${{secrets.TOKEN}}@github.com/sabikrahat/kick_start.git
#           git checkout -b gh-pages
#           git add --all
#           git commit -m "update"
#           git push origin gh-pages -f